language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t sameeranbandishti/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true USERNAME/react-test npm test

after_success:
  - docker build -t sameeranbandishti/multi-client ./client
  - docker build -t sameeranbandishti/multi-nginx ./nginx
  - docker build -t sameeranbandishti/multi-server ./server
  - docker build -t sameeranbandishti/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push sameeranbandishti/multi-client
  - docker push sameeranbandishti/multi-nginx
  - docker push sameeranbandishti/multi-server
  - docker push sameeranbandishti/multi-worker